[project]
name = "ecommerce-data-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.43.108",
    "faker>=40.40.0",
    "pandas>=3.0.6",
    "psycopg2-binary>=2.9.13",
    "pyarrow>=25.0.1",
    "python-dotenv>=1.2.4",
]
